### ISSUE TITLE
Category support

### ISSUE THREAD

**Issue by jeeftor** [asymworks/pyairnow#8]
![image](https://github.com/asymworks/pyairnow/assets/6491743/63785cfb-5bc8-4107-907e-a799c3a329b5)

I was looking at adding some extended attributes for the category to the home assistant AirNow integration and I noticed this is the backing lib and I'm not sure its in here.

The API does provide it ... so I thought I'd open an issue ... I'm happy to fork/PR if need-be but I also like to let people who wrote the code implement their own changes

**Comment by jeeftor** [comment]
Probably I should run. your code and see if your pulling it in anyways... It doesn't look like you are making custom data models so its probalby here

**Comment by asymworks** [comment]
I might not be following your question - this library is intended to be a thin wrapper around the API and expose everything it receives from AirNow directly to HA, without any editing.  It does pick up the category information for my location at least.  If it's missing something, let me know and I can investigate why it's not getting passed over.

**Comment by jeeftor** [comment]
It’s there. I closed thisSent from my iPhoneOn Mar 3, 2024, at 10:17 AM, J.P. Krauss ***@***.***> wrote:﻿
I might not be following your question - this library is intended to be a thin wrapper around the API and expose everything it receives from AirNow directly to HA, without any editing.  It does pick up the category information for my location at least.  If it's missing something, let me know and I can investigate why it's not getting passed over.
